// GENERATED by scripts/update-obsidian-mobile.js — do not edit.
//
// Single source of truth for the currently-vendored Obsidian mobile version
// string. The string used to be duplicated (an inline object-literal in
// capacitor-shim.js's App.getInfo(), plus assorted fallbacks) — see
// docs/plans/electron-shim-foundation.md §3.0 for why that was unsafe: the
// bundle's own top-level `En(function (e) { Uee = e.ipcRenderer.sendSync
// ("version") })` OVERWRITES a valid default the instant `require('electron')`
// starts returning something, so every reader of the version string needs the
// SAME correct value, not a plausible-looking placeholder.
//
// Regenerated by `node scripts/update-obsidian-mobile.js [--version X.Y.Z]`
// every time the vendored bundle is updated — committed so a fresh checkout
// that never ran the script still has a valid value.
window.__owObsidianVersion = '1.12.7';
